apiVersion: v1
kind: Namespace
metadata:
  name: opensearch
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: opensearch
spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: opensearch
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: opensearch
spec:
  serviceName: opensearch
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2
          ports:
            - containerPort: 9200
            - containerPort: 9600
          env:
            - name: discovery.type
              value: single-node
            - name: plugins.security.disabled
              value: "true"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /usr/share/opensearch/data
          resources:
            requests:
              memory: "3Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1000m"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 20Gi
