apiVersion: v1
kind: Service
metadata:
  name: rails-app
  namespace: rails-app
  labels:
    app.kubernetes.io/name: rails-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rails-app
  ports:
    - port: 80
      targetPort: 3000
      name: http
